language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
branches:
  only:
    - master
before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: 
      - ./mvnw clean package

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - tonymkcv93@gmail.com 
deploy:
  - provider: s3
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: my-nonstop-deploy # 6-3-3에서 생성한 S3 버킷
    key: springboot-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: nonstopdeploy-app # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: hoonsbory/nonstopDeploy #Github 주소
      branch: master